-- =====================================================================
-- STARTER PRODUCTS (run once, AFTER schema.sql)
-- Loads the 58 products that were in the original website.
-- image_url points at the photos inside the website folder; photos you
-- upload later through the owner dashboard get a full web address instead.
-- Running this twice is safe: existing products are left alone.
-- =====================================================================
insert into public.products (id, name, category, price, was, tag, stock, image_url, description) values
  ('bag1', 'Ivory Teddy-Embossed Boston Bag', 'Bags', 13500, null, 'new', 10, 'images/products/bags/bag1.webp', 'A Boston-style bag with a rounded, roomy shape for the office and for travel days.'),
  ('bag2', 'Purple Floral Patent Tote & Purse Set', 'Bags', 27500, null, null, 5, 'images/products/bags/bag2.webp', 'A statement tote with a matching purse, made for carrying your daily essentials in style.'),
  ('bag3', 'Burgundy Woven Knot Shoulder Bag', 'Bags', 16800, 20500, 'deal', 7, 'images/products/bags/bag3.webp', 'A shoulder bag with a woven knot detail, easy to wear from work to the weekend.'),
  ('bag4', 'Tan Mini Top-Handle Satchel', 'Bags', 9200, null, null, 12, 'images/products/bags/bag4.webp', 'A compact top-handle satchel, small enough to be easy and smart enough for any occasion.'),
  ('bag5', 'Navy Colourblock Tote & Mini Bag Set', 'Bags', 24000, null, null, 6, 'images/products/bags/bag5.webp', 'A full-size tote with a matching mini bag, for days that move from work to evening.'),
  ('bag6', 'Rosewood Quilted 3-Piece Bag Set', 'Bags', 22500, null, 'new', 8, 'images/products/bags/bag6.webp', 'A coordinated bag set with matching pieces, so your look comes together in one purchase.'),
  ('bag7', 'Navy Floral Patent Tote & Purse Set', 'Bags', 27500, null, null, 4, 'images/products/bags/bag7.webp', 'A statement tote with a matching purse, made for carrying your daily essentials in style.'),
  ('bag8', 'Cognac Woven Knot Shoulder Bag', 'Bags', 16800, null, null, 9, 'images/products/bags/bag8.webp', 'A shoulder bag with a woven knot detail, easy to wear from work to the weekend.'),
  ('bag9', 'Emerald Floral Patent Tote & Purse Set', 'Bags', 27500, null, 'new', 3, 'images/products/bags/bag9.webp', 'A statement tote with a matching purse, made for carrying your daily essentials in style.'),
  ('bag10', 'Black Floral Patent Tote & Purse Set', 'Bags', 27500, null, null, 6, 'images/products/bags/bag10.webp', 'A statement tote with a matching purse, made for carrying your daily essentials in style.'),
  ('bag11', 'Espresso Woven Knot Shoulder Bag', 'Bags', 16800, null, null, 0, 'images/products/bags/bag11.webp', 'A shoulder bag with a woven knot detail, easy to wear from work to the weekend.'),
  ('bag12', 'Emerald Pleated Satin Clutch', 'Bags', 14500, null, null, 11, 'images/products/bags/bag12.webp', 'A pleated satin clutch for weddings, dinners and evenings out. Slim enough to carry in one hand.'),
  ('bag13', 'Silver Pleated Satin Clutch', 'Bags', 14500, null, 'new', 13, 'images/products/bags/bag13.webp', 'A pleated satin clutch for weddings, dinners and evenings out. Slim enough to carry in one hand.'),
  ('bag14', 'Emerald Croc-Embossed Structured Tote', 'Bags', 29500, 35000, 'deal', 2, 'images/products/bags/bag14.webp', 'A structured tote with room for your daily essentials.'),
  ('bag15', 'Ivory Classic Boston Bag', 'Bags', 18500, null, null, 15, 'images/products/bags/bag15.webp', 'A Boston-style bag with a rounded, roomy shape for the office and for travel days.'),
  ('bag16', 'Taupe Croc-Embossed 3-Piece Bag Set', 'Bags', 23500, null, null, 5, 'images/products/bags/bag16.webp', 'A coordinated bag set with matching pieces, so your look comes together in one purchase.'),
  ('bag17', 'Silver Sequin Bucket Bag', 'Bags', 19800, null, 'new', 4, 'images/products/bags/bag17.webp', 'A bucket-shaped bag with a sparkle finish that dresses up an evening look.'),
  ('bag18', 'Blush Croc-Embossed 3-Piece Bag Set', 'Bags', 23500, null, null, 7, 'images/products/bags/bag18.webp', 'A coordinated bag set with matching pieces, so your look comes together in one purchase.'),
  ('bag19', 'Black Woven Knot Shoulder Bag', 'Bags', 16800, null, null, 10, 'images/products/bags/bag19.webp', 'A shoulder bag with a woven knot detail, easy to wear from work to the weekend.'),
  ('bag20', 'Black Tweed Chain Flap Bag', 'Bags', 21500, 26000, 'deal', 6, 'images/products/bags/bag20.webp', 'A chain-strap flap bag in a classic tweed finish that goes with almost anything.'),
  ('bag21', 'Taupe Pebbled Leather Shoulder Bag', 'Bags', 17500, null, null, 9, 'images/products/bags/bag21.webp', 'A shoulder bag cut for daily use, with room for your phone, wallet and essentials.'),
  ('bag22', 'Black Mini Top-Handle Satchel', 'Bags', 9200, null, null, 11, 'images/products/bags/bag22.webp', 'A compact top-handle satchel, small enough to be easy and smart enough for any occasion.'),
  ('bag23', 'Purple Croc-Embossed Structured Tote', 'Bags', 29500, null, 'new', 4, 'images/products/bags/bag23.webp', 'A structured tote with room for your daily essentials.'),
  ('bag24', 'Black Belted Tote with Charm Pouch', 'Bags', 26500, null, null, 5, 'images/products/bags/bag24.webp', 'A belted tote that comes with a charm pouch, for extra storage and a finishing touch.'),
  ('bag25', 'Ivory Pleated Satin Clutch', 'Bags', 14500, null, null, 10, 'images/products/bags/bag25.webp', 'A pleated satin clutch for weddings, dinners and evenings out. Slim enough to carry in one hand.'),
  ('bag26', 'White Croc-Trim Tote with Charm Pouch', 'Bags', 26500, null, 'new', 3, 'images/products/bags/bag26.webp', 'A belted tote that comes with a charm pouch, for extra storage and a finishing touch.'),
  ('bag27', 'Black Pebbled Leather Shoulder Bag', 'Bags', 17500, null, null, 8, 'images/products/bags/bag27.webp', 'A shoulder bag cut for daily use, with room for your phone, wallet and essentials.'),
  ('bag28', 'Red Belted Tote with Charm Pouch', 'Bags', 26500, 31500, 'deal', 4, 'images/products/bags/bag28.webp', 'A belted tote that comes with a charm pouch, for extra storage and a finishing touch.'),
  ('bag29', 'Silver Mini Top-Handle Satchel', 'Bags', 9200, null, null, 7, 'images/products/bags/bag29.webp', 'A compact top-handle satchel, small enough to be easy and smart enough for any occasion.'),
  ('bag30', 'Black Sequin Chain Bucket Bag', 'Bags', 18800, null, null, 6, 'images/products/bags/bag30.webp', 'A bucket-shaped bag with a sparkle finish that dresses up an evening look.'),
  ('bag31', 'Wine Boston Bag with Strap Detail', 'Bags', 15800, null, null, 12, 'images/products/bags/bag31.webp', 'A Boston-style bag with a rounded, roomy shape for the office and for travel days.'),
  ('bag32', 'Black Slouchy Shoulder Bag', 'Bags', 17500, 21000, 'deal', 10, 'images/products/bags/bag32.webp', 'A shoulder bag cut for daily use, with room for your phone, wallet and essentials.'),
  ('bag33', 'Brown Flap Crossbody Bag', 'Bags', 16200, null, null, 9, 'images/products/bags/bag33.webp', 'A flap crossbody bag that keeps your hands free and your essentials close.'),
  ('bag34', 'Silver Metallic Woven Knot Bag', 'Bags', 17800, null, 'new', 6, 'images/products/bags/bag34.webp', 'A shoulder bag with a woven knot detail, easy to wear from work to the weekend.'),
  ('bag35', 'Blush Mini Top-Handle Satchel', 'Bags', 9200, null, null, 8, 'images/products/bags/bag35.webp', 'A compact top-handle satchel, small enough to be easy and smart enough for any occasion.'),
  ('bag36', 'Magenta Pleated Satin Clutch', 'Bags', 14500, null, null, 11, 'images/products/bags/bag36.webp', 'A pleated satin clutch for weddings, dinners and evenings out. Slim enough to carry in one hand.'),
  ('bag37', 'Black Paillette Bucket Bag', 'Bags', 18800, null, null, 5, 'images/products/bags/bag37.webp', 'A bucket-shaped bag with a sparkle finish that dresses up an evening look.'),
  ('bag38', 'Black Quilted 3-Piece Bag Set', 'Bags', 23500, null, null, 6, 'images/products/bags/bag38.webp', 'A coordinated bag set with matching pieces, so your look comes together in one purchase.'),
  ('bag39', 'Caramel Quilted 3-Piece Bag Set', 'Bags', 23500, null, 'new', 7, 'images/products/bags/bag39.webp', 'A coordinated bag set with matching pieces, so your look comes together in one purchase.'),
  ('bag40', 'Crimson Mini Top-Handle Satchel', 'Bags', 9200, null, null, 10, 'images/products/bags/bag40.webp', 'A compact top-handle satchel, small enough to be easy and smart enough for any occasion.'),
  ('bag41', 'Black Leather Business Briefcase', 'Bags', 26500, null, null, 6, 'images/products/bags/bag41.webp', 'A business briefcase with a clean, professional look for work and meetings.'),
  ('bag42', 'White Croc-Embossed Buckle Shoulder Bag', 'Bags', 19800, null, 'new', 8, 'images/products/bags/bag42.webp', 'A shoulder bag cut for daily use, with room for your phone, wallet and essentials.'),
  ('bag43', 'Black Croc-Embossed Buckle Shoulder Bag', 'Bags', 19800, null, null, 9, 'images/products/bags/bag43.webp', 'A shoulder bag cut for daily use, with room for your phone, wallet and essentials.'),
  ('bag44', 'Black Anti-Theft Tech Backpack', 'Bags', 23500, 28000, 'deal', 7, 'images/products/bags/bag44.webp', 'An anti-theft backpack made for work, school and daily commutes.'),
  ('a1', 'Electric kettle 1.8L, stainless steel body', 'Appliances', 9500, null, null, 11, null, 'A 1.8L stainless steel electric kettle for fast tea, coffee and hot water.'),
  ('a2', 'Blender and grinder combo, 2-in-1 kitchen set', 'Appliances', 18000, 21500, 'deal', 5, null, 'A 2-in-1 blender and grinder set for smoothies, sauces and spices.'),
  ('a3', 'Standing fan 18-inch, 3 speed adjustable', 'Appliances', 22500, null, null, 8, null, 'An 18-inch standing fan with three speed settings and an adjustable stand.'),
  ('a4', 'Rice cooker 1.5L, non-stick inner pot', 'Appliances', 14000, null, 'new', 17, null, 'A 1.5L rice cooker with a non-stick inner pot, easy to cook with and easy to clean.'),
  ('a5', 'Dry pressing iron, lightweight home use', 'Appliances', 7800, null, null, 2, null, 'A lightweight dry pressing iron for everyday home use.'),
  ('a6', 'Mini fridge 50L, compact for bedroom or office', 'Appliances', 95000, null, null, 4, null, 'A compact 50L mini fridge, sized for a bedroom or office.'),
  ('app7', 'Green 4-Compartment Lunch Box + Soup Bowl', 'Appliances', 7800, null, 'new', 18, 'images/products/appliances/app7.webp', 'A compartment lunch box with a soup bowl, for carrying a full meal to work or school.'),
  ('app8', 'Blue 5-Compartment Lunch Box + Soup Bowl', 'Appliances', 8200, null, null, 14, 'images/products/appliances/app8.webp', 'A compartment lunch box with a soup bowl, for carrying a full meal to work or school.'),
  ('app9', 'Green 5-Compartment Lunch Box + Soup Bowl', 'Appliances', 8200, null, null, 11, 'images/products/appliances/app9.webp', 'A compartment lunch box with a soup bowl, for carrying a full meal to work or school.'),
  ('app10', 'Blue 4-Compartment Lunch Box + Soup Bowl', 'Appliances', 7800, null, null, 16, 'images/products/appliances/app10.webp', 'A compartment lunch box with a soup bowl, for carrying a full meal to work or school.'),
  ('app11', 'Pink Compartment Lunch Box Set', 'Appliances', 7800, 9500, 'deal', 9, 'images/products/appliances/app11.webp', 'A compartment lunch box with a soup bowl, for carrying a full meal to work or school.'),
  ('app12', 'Manual Food Chopper 1.5L', 'Appliances', 11500, null, null, 10, 'images/products/appliances/app12.webp', 'A manual food chopper for vegetables and herbs, no electricity needed.'),
  ('app13', 'Manual Food Chopper 0.7L', 'Appliances', 8500, null, 'new', 13, 'images/products/appliances/app13.webp', 'A manual food chopper for vegetables and herbs, no electricity needed.'),
  ('app14', 'Manual Food Chopper 2.0L', 'Appliances', 14500, null, null, 7, 'images/products/appliances/app14.webp', 'A manual food chopper for vegetables and herbs, no electricity needed.')
on conflict (id) do nothing;
